### ISSUE TITLE
Risk of deadlock in the subscribe handler

### ISSUE THREAD

**Issue by klaxalk** [ctu-mrs/mrs_lib#23]
Check the diff. A deadlock might occur between
1. `topicName()` (which locks `m_mtx`) being called in `check_timeout()`, and
2. `process_new_message()` (being under `m_mtx`), calling `m_timeout_check_timer.stop()` that is blocking until it is sure no more `check_timeout()` will get called (aka, until 1. finishes).

Code noticing before it happens: [https://github.com/ctu-mrs/mrs_lib/compare/deadlock_notice](https://github.com/ctu-mrs/mrs_lib/compare/deadlock_notice)
GDB backtrace: [backtrace.txt](https://github.com/ctu-mrs/mrs_lib/files/6269713/backtrace.txt)

**Comment by matemat13** [comment]
should be fixed with 1d352d7, reopen if necessary
