### ISSUE TITLE
Check if SubscribeHandlers's topic timeout actually works

### ISSUE THREAD

**Issue by klaxalk** [ctu-mrs/mrs_lib#28]
Control mananger did not properly time out the UAV state topic from odometry. It might have been caused by the high CPU load which caused the topic to be missing in the first place. Maybe implementing the timeout check by some other mechanism than ROS timer?

**Comment by matemat13** [comment]
@klaxalk so you found out it was a bug on your side then? Can I close this issue?

**Comment by klaxalk** [comment]
Ye, it works, thanks!
