### ISSUE TITLE
Timeout for BatchVisualization

### ISSUE THREAD

**Issue by WingRS** [ctu-mrs/mrs_lib#42]
It would be nice to implement a timeout for a cuboid/line visualization feature. 
For example, it would look like this
``
void mrs_lib::BatchVisualizer::addCuboid 	( 	const [mrs_lib::geometry::Cuboid](https://ctu-mrs.github.io/mrs_lib/classmrs__lib_1_1geometry_1_1Cuboid.html) &  	cuboid,
		const double  	r = 0.5,
		const double  	g = 0.5,
		const double  	b = 0.0,
		const double  	a = 1.0,
		const bool  	filled = true,
               const ros::Duration timeout = 1
	)
``

The clearBuffer function is nice, but having an automatic option would be nice.

**Comment by stibipet** [comment]
Nice idea, done! https://github.com/ctu-mrs/mrs_lib/pull/43
